language: rust
sudo: false

cache:
  ccache: true
  directories:
    - ${HOME}/.ccache

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.8
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

env:
  global:
    - USE_C_COMPILERACHE=1
    - C_COMPILERACHE_COMPRESS=1
    - C_COMPILERACHE_MAXSIZE=200M
    - C_COMPILERACHE_CPP2=1
    - CC='ccache clang-3.8'
    - CXX='ccache clang++-3.8'
    - CFLAGS='-Wno-error=unused-command-line-argument'
    - CXXFLAGS='-Wno-error=unused-command-line-argument'
    - LOCAL=${HOME}/.local
    - PATH=${LOCAL}/bin:${PATH}

before_script:
  - cmake --version
  - ${CC} --version
  - ${CXX} --version

after_failure: cat build.log

after_success:
  - git clone https://github.com/SimonKagstrom/kcov.git
  - mkdir kcov/build
  - cd kcov/build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=${LOCAL} ..
  - make -j $(nproc)
  - make install
  - cd ../..
  - kcov --coveralls-id=${TRAVIS_JOB_ID} --exclude-pattern=/.cargo target/kcov target/debug/bobyqa-*
