language: rust
sudo: false

cache:
  ccache: true
  directories:
    - ${HOME}/.ccache

addons:
  apt:
    sources: ['llvm-toolchain-precise', 'ubuntu-toolchain-r-test']
    packages: ['clang-3.8']

env:
  global:
    - USE_C_COMPILERACHE=1
    - C_COMPILERACHE_COMPRESS=1
    - C_COMPILERACHE_MAXSIZE=200M
    - C_COMPILERACHE_CPP2=1
    - CC='ccache clang-3.8'
    - CXX='ccache clang++-3.8'
    - CFLAGS='-Wno-error=unused-command-line-argument'
    - CXXFLAGS='-Wno-error=unused-command-line-argument'

before_script:
  - cmake --version
  - ${CC} --version
  - ${CXX} --version

after_failure: cat build.log
